language: java
branches:
  only:
    - api-ingestor
notifications:
  email:
    - arbhagwa@umail.iu.edu
    - laxmalka@umail.iu.edu
    - pcpeters@umail.iu.edu
    - tilaks@umail.iu.edu
jdk:
  - oraclejdk8
sudo: false
install: true
script: mvn clean install -DskipTests=true