language: python

python:
  - "3.3"
# command to install dependencies

branches:
  only:
    - api-runforecast-release

sudo: required

before_install:
  # Install ZooKeeper
  - "sudo apt-get install zookeeperd"

install: "pip install -r runforecast/requirements.txt"

before_script:
  - "sudo service zookeeper init"
  - "sudo service zookeeper start"

before_script:
  - pip install virtualenv
  - cd runforecast
  - virtualenv env
  - source env/bin/activate
  - pip install requests
  - pip install httplib2
  - pip install nose
  - pip install Flask-SQLAlchemy
  - pip install kazoo

script: nosetests

after_script:
  - "sudo service zookeeper stop"

services:
  - docker

after-success:
  - cd ..

before_deploy:
  - cd /home/travis/build/airavata-courses/TeamAviato
  - zip -r SGA_TeamAviato_RunForeCast.zip scripts runforecast appspec.yml || true
  - mkdir -p "runForecast"
  - mv SGA_TeamAviato_RunForeCast.zip runForecast/SGA_TeamAviato_RunForeCast.zip || true

deploy:  
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket-ohio
    local_dir: runForecast
    region: us-east-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: api-runforecast-release

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket-ohio
    key: SGA_TeamAviato_RunForeCast.zip
    bundle_type: zip
    application: TeamAviatoApp-ohio
    deployment_group: TeamAviatoApp-ohio
    region: us-east-2
    skip_cleanup: true
    on:
      branch: api-runforecast-release

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket-ohio
    local_dir: runForecast
    region: us-east-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: api-runforecast-release

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket-ohio
    key: SGA_TeamAviato_RunForeCast.zip
    bundle_type: zip
    application: TeamAviatoApp-ohio2
    deployment_group: TeamAviatoApp-ohio2
    region: us-east-2
    skip_cleanup: true
    on:
      branch: api-runforecast-release

  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket2
    local_dir: runForecast
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on: 
      branch: api-runforecast-release

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket2
    key: SGA_TeamAviato_RunForeCast.zip
    bundle_type: zip
    application: TeamAviatoApp
    deployment_group: TeamAviatoApp
    region: us-west-2
    skip_cleanup: true
    on:
      branch: api-runforecast-release
      
after_deploy:
  - echo "Performing after deploy procedures..."
  - done
  
notifications:
  email:
    - laxmibh.malkareddy@gmail.com
    
