language: java
branches:
  only:
    - api-ingestor
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

install:
  - cd "api-ingestor" && mvn clean install -DskipTests=true
  - docker build -t tilaks/dataingestor ../.
  - docker ps -a
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push tilaks/dataingestor

script: mvn clean install -DskipTests=true

before_deploy:
  - cd ..
  - zip -r SGA_Aviato_DataIngestor.zip api-ingestor scripts appspec.yml || true
  - mkdir -p "dpl_cd_upload"
  - mv SGA_Aviato_DataIngestor.zip dpl_cd_upload/SGA_Aviato_DataIngestor.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket2
    local_dir: dpl_cd_upload
    region: us-west-2
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: api-ingestor

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket2
    key: SGA_Aviato_DataIngestor.zip
    bundle_type: zip
    application: TeamAviatoApp
    deployment_group: TeamAviatoApp
    region: us-west-2
    skip_cleanup: true
    on:
      branch: api-ingestor
