language: python

python:
  - "3.3"

# command to install dependencies
sudo: required

before_install:
  # Install ZooKeeper
  - "sudo apt-get install zookeeperd"

install: "pip install -r forecasttrigger/requirements.txt"

before_script:
  - "sudo service zookeeper init"
  - "sudo service zookeeper start"

before_script:
  - pip install virtualenv
  - cd forecasttrigger
  - virtualenv env
  - source env/bin/activate
  - pip install requests
  - pip install httplib2
  - pip install nose
  - pip install Flask-SQLAlchemy
  - pip install kazoo

script: nosetests

after_script:
  - "sudo service zookeeper stop"

services:
  - docker

after-success:
  - cd ..

before_deploy:
  - zip -r SGA_TeamAviato_ForecastTrigger.zip forecasttrigger scripts appspec.yml || true
  - mkdir -p "forecastTrigger"
  - mv SGA_TeamAviato_ForecastTrigger.zip forecastTrigger/SGA_TeamAviato_ForecastTrigger.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket2
    skip_cleanup: true
    local-dir: forecastTrigger
    acl: public_read
    region: us-west-2	
    detect_encoding: true
    on: 
      branch: api-forecasttrigger
      
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: teamaviatobucket2
    key: SGA_TeamAviato_ForecastTrigger.zip
    bundle_type: zip
    application: TeamAviatoApp
    deployment_group: TeamAviatoApp
    region: us-west-2
    on:
      branch: api-forecasttrigger
      

after_deploy:
  - echo "Performing after deploy procedures..."
  - done
  
notifications:
  email:
    - laxmibh.malkareddy@gmail.com
