language: python

python:
  - "3.3"
# command to install dependencies
install: "pip install -r stormdetection/requirements.txt"

before_script:
  - pip install virtualenv
  - cd stormdetection
  - virtualenv env
  - source env/bin/activate
  - pip install requests
  - pip install httplib2
  - pip install nose
  - pip install Flask-SQLAlchemy

script: nosetests 

services:
  - docker

before_deploy:
  - cd ..
  - zip -r SGA_TeamAviato_StormDetector_Test.zip stormdetection scripts appspec.yml || true
  - mkdir -p "stormDetection"
  - mv SGA_TeamAviato_StormDetector_Test.zip stormDetection/SGA_TeamAviato_StormDetector_Test.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: team-aviato-bucket-test
    skip_cleanup: true
    local-dir: stormDetection
    acl: public_read
    region: us-west-2
    detect_encoding: true
    on: 
      branch: api-stormdetector-test
      
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: team-aviato-bucket-test
    key: SGA_TeamAviato_StormDetector_Test.zip
    bundle_type: zip
    application: TeamAviatoApp
    deployment_group: TeamAviatoApp
    region: us-west-2
    on:
      branch: api-stormdetector-test
    

after_deploy:
  - echo "Performing after deploy procedures..."
  - done
  
notifications:
  email:
    - laxmibh.malkareddy@gmail.com
    
