language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"

# command to test service
script: cd "stormclustering" && python test_stormclustering.py