language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
# command to install dependencies
install: "pip install -r stormdetection/requirements.txt"

# command to run tests
script: cd "stormdetection" && python test_storm_detector.py